name: test
on:
  pull_request:
  workflow_call:
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add local packages source
      env:
        READ_REPO_PACKAGES: ${{ secrets.READ_REPO_PACKAGES }}
      run: dotnet nuget add source --name ne14-gp --username ne14-gp --password "${{ env.READ_REPO_PACKAGES }}" --store-password-in-clear-text "https://nuget.pkg.github.com/ne14-golden-path/index.json"
    - name: Restore tools
      run: dotnet tool restore
    - name: Build for release (failing build warnings)
      run: dotnet build -c Release --no-incremental /warnaserror
